name: SAMPL
url: http://uwSAMPL.github.io # Update to be CS web address

exclude: [bibble, README.md, Makefile, screenshot.png]

# Colorize code snippets with the rogue module if we want to deploy on GH.
highlighter: rouge

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Sections on the "people" page.
roles:
  - key: faculty
    name: Faculty
  # Restore me when we add some staff
  # - key: staff
  #   name: Staff
  - key: postdoc
    name: Researchers
  - key: visitor
    name: Visiting Graduate Students
  - key: grad
    name: Graduate Students
  - key: ugrad
    name: Undergraduate Students
  - key: ugrad-alum
    name: Past Undergraduate Students
  - key: collab
    name: Collaborators
  - key: alum
    name: Alumni

# Number of news stories on the front page.
front_page_news: 5

# Base pathname for links.
base: ''

# make pages for the _projects folder
collections:
  projects:
    output: true

# Navigation bar links.
navigation:
  - title: Home
    link: /
  - title: People
    link: /#people
  - title: Research
    link: /research.html
  - title: Blog
    link: /blog.html
  - title: Publications
    link: /publications.html
  - title: Talks
    link: /talks.html
  - title: Code
    link: /code.html

plugins:
  - jekyll-redirect-from
